/// Flutter icons RadarApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
// /   fonts:
// /    - family:  RadarApp
// /      fonts:
// /       - asset: fonts/RadarApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RadarApp {
  RadarApp._();

  static const _kFontFam = 'RadarApp';
  static const String? _kFontPkg = null;

  static const IconData minus_sign = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_sign = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swap_location = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
